import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, HelpCircle } from 'lucide-react'
import PageBreadcrumb from '@/components/ui/PageBreadcrumb'
import { createMetadata, siteConfig } from '@/lib/site'

export const metadata: Metadata = createMetadata({
  title: 'Bioculture for Wastewater Treatment FAQs | Bionics Enviro Tech',
  description: 'Answers about bioculture, aerobic and anaerobic bacteria, ETP, STP and septic-tank biological treatment from Bionics Enviro Tech.',
  path: '/faqs',
  keywords: ['what is bioculture', 'bioculture for ETP', 'bioculture for STP', 'aerobic bacteria culture', 'anaerobic bacteria culture'],
})

const faqs = [
  { question: 'What is bioculture?', answer: 'Bioculture is a selected mixture of beneficial microorganisms used to support biological wastewater treatment. These microorganisms help convert compatible biodegradable organic matter into simpler end products under suitable operating conditions. Bioculture does not remove every pollutant and must be selected according to the wastewater and treatment process.' },
  { question: 'What are the uses of bacteria in wastewater treatment?', answer: 'Wastewater bacteria help degrade biodegradable organic matter from domestic sewage, food residues and compatible industrial streams. In a properly designed treatment plant, microbial activity supports BOD and COD reduction before treated water is discharged or reused. Screening, aeration, clarification, disinfection and other required processes remain essential.' },
  { question: 'What is bioculture for an STP?', answer: 'STP bioculture is a microbial formulation used to support the biological stage of a sewage treatment plant. It helps active biomass process compatible organic matter in domestic and commercial sewage. Results depend on aeration, pH, temperature, retention time, loading, sludge condition and plant operation.' },
  { question: 'What is bioculture for an ETP?', answer: 'ETP bioculture is a blend of beneficial microorganisms selected to support degradation of compatible biodegradable pollutants in industrial effluent. It can help biological treatment manage organic load, oils and grease after suitable source control and pretreatment. It does not replace physical, chemical or advanced treatment required for toxic or non-biodegradable contaminants.' },
  { question: 'What are aerobic and anaerobic bacteria cultures?', answer: 'Aerobic bacteria cultures require dissolved oxygen and are commonly used in aeration tanks and aerobic biological reactors. Anaerobic bacteria cultures operate without supplied oxygen and convert high-strength biodegradable organic matter through staged digestion, producing biogas under suitable conditions. Product selection depends on the installed process and wastewater analysis.' },
  { question: 'What are aerobic bacteria?', answer: 'Aerobic bacteria are microorganisms that use oxygen while metabolising compatible organic matter. In wastewater treatment they form part of the active biomass used for biological oxidation. Stable performance requires suitable dissolved oxygen, pH, nutrients, temperature and loading—not bacteria alone.' },
  { question: 'How are living bacteria used in a septic tank?', answer: 'A compatible living-bacteria culture may support digestion of biodegradable material in a functioning septic system. Application should follow a technical assessment and the approved product instructions. Excess disinfectants, acids, alkalis, solvents and chemical toilet cleaners can inhibit microbial activity. Bioculture does not replace desludging, inspection or repair of a damaged or overloaded septic system.' },
  { question: 'What are septic-tank bacteria?', answer: 'Septic-tank bacteria are microorganisms involved in the breakdown of biodegradable solids under low-oxygen or anaerobic conditions. A supplemental culture can support an assessed system, but safe performance still depends on tank capacity, retention time, chemical exposure, sludge accumulation and scheduled maintenance.' },
  { question: 'Is Nanozyme safe for the environment?', answer: 'Nanozyme is an organic biological formulation intended to support controlled wastewater treatment. It should be stored, handled and applied according to the supplied instructions, applicable safety documentation and approved dosage plan. Treated-water discharge or reuse must still meet the relevant regulatory requirements.' },
  { question: 'Can Nanozyme be used in low-pH or high-TDS conditions?', answer: 'Suitability depends on the actual pH, TDS composition, conductivity, toxicity and biological process. Extreme pH should be corrected before biological treatment, and high TDS may inhibit microorganisms or require a separate treatment process. Wastewater analysis is required before selecting a grade.' },
  { question: 'Is Nanozyme certified or tested for use in wastewater treatment?', answer: 'Bionics formulations are supported by the company’s approved product specifications, laboratory knowledge and application experience. Certification or test documentation should be confirmed for the specific product, market and procurement requirement rather than assumed from a general product description.' },
  { question: 'How does Nanozyme bioculture perform during the rainy season?', answer: 'Rain can dilute wastewater, reduce temperature and alter hydraulic loading and retention time. Nanozyme can support the biological process when equalisation, aeration, biomass retention and dosing are adjusted using actual plant data. Seasonal performance is therefore plant- and weather-dependent.' },
  { question: 'Can Nanozyme handle sudden hydraulic-load increases due to rain?', answer: 'It may support biomass resilience, but microbial culture alone cannot prevent hydraulic washout or compensate for inadequate plant capacity. Inflow control, equalisation, return-sludge management, aeration and retention time should be reviewed during rainfall-related load increases.' },
  { question: 'Can Nanozyme replace chemical dosing?', answer: 'Nanozyme may reduce dependence on some corrective chemicals where biodegradable organic treatment improves, but it does not replace every chemical or physicochemical stage. pH correction, coagulation, disinfection, nutrient addition or specialist contaminant treatment may still be required.' },
  { question: 'How long does it take to see visible changes in BOD or COD?', answer: 'An initial biological response may become visible over approximately 24–72 hours in a compatible and well-operated system. Verified BOD and COD improvement should be confirmed through representative laboratory testing over complete treatment cycles, not appearance alone.' },
  { question: 'How fast does Nanozyme show stable results?', answer: 'Stable performance normally takes longer than the first visible response. The period depends on wastewater characteristics, temperature, loading, biomass condition, retention time, aeration and the selected application programme. Trend data should be reviewed before concluding that the plant has stabilised.' },
  { question: 'What is the dosage of Nanozyme bioculture for industrial STPs and ETPs?', answer: 'There is no responsible universal dose. Dosage depends on plant capacity, influent COD and BOD, biodegradability, MLSS, dissolved oxygen, process configuration, toxicity and treatment objective. The final grade, activation volume and maintenance dose require technical assessment.' },
  { question: 'Is Nanozyme bioculture suitable for sugar mills and distilleries?', answer: 'Bionics provides application-specific cultures for sugar-mill ETPs, distillery wastewater, anaerobic digestion and related composting programmes. Selection depends on whether the treatment stage is aerobic, anaerobic, fermentation-related or composting, together with feed and wastewater analysis.' },
  { question: 'Can Nanozyme be used in municipal CSTPs and decentralised STPs?', answer: 'It can support compatible municipal, community and decentralised sewage-treatment systems after the process, loading and biomass condition have been assessed. Screening, aeration, clarification, sludge management and validated disinfection remain necessary.' },
  { question: 'Is it safe to handle and apply Nanozyme?', answer: 'Use the recommended personal protective equipment and follow the product label, storage instructions and applicable safety documentation. Avoid ingestion, unnecessary inhalation and contact with eyes or broken skin, and ensure that trained personnel perform preparation and dosing.' },
  { question: 'Can I request a demonstration or free consultation before a bulk order?', answer: 'Yes. Share the plant capacity, treatment process, recent influent and outlet analysis, operating data and treatment objective with Bionics Enviro Tech. The team can review the application and advise whether a consultation, demonstration or trial programme is appropriate.' },
]

export default function FaqsPage() {
  const pageUrl = `${siteConfig.url}/faqs`
  const schemas = [
    { '@context': 'https://schema.org', '@type': 'WebPage', name: 'Bioculture for Wastewater Treatment FAQs', url: pageUrl, description: 'Technical answers about wastewater treatment bioculture for ETP, STP and septic systems.' },
    { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: siteConfig.url }, { '@type': 'ListItem', position: 2, name: 'Resources', item: `${siteConfig.url}/blogs` }, { '@type': 'ListItem', position: 3, name: 'FAQs', item: pageUrl }] },
    { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map(item => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) },
  ]
  return <main className="min-h-screen bg-slate-50 pb-20 pt-28">{schemas.map((schema, index) => <script key={index} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />)}<div className="mx-auto max-w-5xl px-5 sm:px-8 lg:px-10"><PageBreadcrumb items={[{ label: 'Resources', href: '/blogs' }, { label: 'FAQs' }]} /><header className="py-10 text-center lg:py-14"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-emerald-100 to-cyan-100 text-emerald-700"><HelpCircle /></span><p className="mt-5 text-xs font-bold uppercase tracking-[.2em] text-emerald-700">Wastewater treatment knowledge</p><h1 className="mx-auto mt-3 max-w-4xl text-4xl font-black tracking-tight text-slate-950 sm:text-6xl">Bioculture Frequently Asked Questions</h1><p className="mx-auto mt-5 max-w-3xl text-lg leading-8 text-slate-600">Clear answers about wastewater treatment bioculture, aerobic and anaerobic bacteria, ETP, STP and septic-system applications.</p></header><section className="space-y-3" aria-label="Bioculture questions and answers">{faqs.map((item, index) => <details key={item.question} className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm open:border-emerald-200 open:shadow-md"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 text-base font-black text-slate-950 sm:text-lg"><span><span className="mr-3 text-emerald-600">{String(index + 1).padStart(2, '0')}</span>{item.question}</span><span aria-hidden className="text-2xl font-light text-emerald-600 transition group-open:rotate-45">+</span></summary><p className="mt-4 border-t border-slate-100 pt-4 leading-7 text-slate-600">{item.answer}</p></details>)}</section><section className="mt-12 rounded-3xl bg-gradient-to-r from-emerald-600 to-cyan-600 p-7 text-white sm:p-10"><h2 className="text-2xl font-black sm:text-3xl">Need an application-specific recommendation?</h2><p className="mt-3 max-w-2xl leading-7 text-white/90">Share your wastewater analysis, process configuration and operating data so the technical team can assess the appropriate product and application approach.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/#contact" className="inline-flex min-h-11 items-center gap-2 rounded-full bg-white px-5 text-sm font-bold text-emerald-800">Request a Quote <ArrowRight className="h-4 w-4" /></Link><Link href="/products" className="inline-flex min-h-11 items-center rounded-full border border-white/40 px-5 text-sm font-bold text-white">Explore Products</Link></div></section></div></main>
}
