import type { Metadata } from 'next'
import Link from 'next/link'
import { Download, Eye, FileText, LockKeyhole } from 'lucide-react'
import PageBreadcrumb from '@/components/ui/PageBreadcrumb'
import { downloads } from '@/data/resource-content'
import { createMetadata, siteConfig } from '@/lib/site'

export const metadata: Metadata = createMetadata({ title: 'Technical Downloads Center | Bionics Enviro Tech', description: 'Access the Bionics company profile and find planned product brochures, industry brochures, certificates, technical datasheets and application guides.', path: '/downloads', keywords: ['Bionics company profile download', 'Nanozyme brochure', 'technical datasheet', 'wastewater treatment downloads'] })

export default function DownloadsPage() {
  const schema = { '@context': 'https://schema.org', '@type': 'CollectionPage', name: 'Bionics Technical Downloads Center', url: `${siteConfig.url}/downloads`, hasPart: downloads.map((item) => ({ '@type': 'DigitalDocument', name: item.title, description: item.description, url: item.href ? `${siteConfig.url}${item.href}` : `${siteConfig.url}/downloads#${item.id}` })) }
  return <main className="min-h-screen bg-slate-50 pb-16 pt-28"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><PageBreadcrumb items={[{ label: 'Downloads' }]} /><header className="max-w-4xl py-10 lg:py-12"><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-700">Documents and brochures</p><h1 className="mt-4 text-4xl font-black text-slate-950 sm:text-6xl">Technical Downloads Center</h1><p className="mt-5 text-lg leading-8 text-slate-600">Download published company material or request controlled technical and application documents.</p></header><section className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{downloads.map((item) => <article id={item.id} key={item.id} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-br from-emerald-100 to-cyan-100 text-emerald-700">{item.href ? <FileText /> : <LockKeyhole />}</div><p className="mt-5 text-xs font-bold uppercase tracking-wider text-cyan-700">{item.category}</p><h2 className="mt-2 text-xl font-black text-slate-950">{item.title}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{item.description}</p><dl className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><dt className="font-bold text-slate-500">File size</dt><dd className="mt-1 text-slate-800">{item.size}</dd></div><div><dt className="font-bold text-slate-500">Updated</dt><dd className="mt-1 text-slate-800">{item.updated}</dd></div></dl><div className="mt-5 flex gap-2">{item.href ? <><a href={item.href} download className="inline-flex min-h-11 flex-1 items-center justify-center gap-2 rounded-xl bg-emerald-600 px-3 text-sm font-bold text-white"><Download className="h-4 w-4" />Download</a><a href={item.href} target="_blank" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-slate-300 px-3 text-sm font-bold text-slate-700"><Eye className="h-4 w-4" />Preview</a></> : <><span className="inline-flex min-h-11 flex-1 items-center justify-center rounded-xl bg-slate-100 px-3 text-sm font-bold text-slate-500">Coming Soon</span><Link href="/#contact" className="inline-flex min-h-11 items-center rounded-xl border border-emerald-600 px-3 text-sm font-bold text-emerald-700">Request</Link></>}</div></article>)}</section></div></main>
}
