import type { Metadata } from 'next'
import Image from 'next/image'
import Link from 'next/link'
import { Download, PhoneCall } from 'lucide-react'
import PageBreadcrumb from '@/components/ui/PageBreadcrumb'
import { caseStudies } from '@/data/resource-content'
import { createMetadata, siteConfig } from '@/lib/site'

export const metadata: Metadata = createMetadata({ title: 'Industrial Wastewater Case Studies | Bionics', description: 'Review representative Nanozyme wastewater treatment case studies covering textile ETP, distillery anaerobic digestion and dairy organic-load improvement.', path: '/case-studies', keywords: ['wastewater treatment case studies', 'ETP case study', 'Nanozyme results', 'COD BOD reduction'] })

export default function CaseStudiesPage() {
  const schemas = caseStudies.map((study) => ({ '@context': 'https://schema.org', '@type': 'Article', headline: study.title, description: study.problem, image: `${siteConfig.url}${study.image}`, author: { '@type': 'Organization', name: siteConfig.name }, publisher: { '@type': 'Organization', name: siteConfig.name }, mainEntityOfPage: `${siteConfig.url}/case-studies#${study.slug}` }))
  return <main className="min-h-screen bg-slate-50 pb-16 pt-28">{schemas.map((schema, index) => <script key={index} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />)}<div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><PageBreadcrumb items={[{ label: 'Case Studies' }]} /><header className="max-w-4xl py-10 lg:py-12"><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-700">Industrial reports</p><h1 className="mt-4 text-4xl font-black text-slate-950 sm:text-6xl">Wastewater Treatment Case Studies</h1><p className="mt-5 text-lg leading-8 text-slate-600">Concise representative reports covering the treatment challenge, implementation approach and reviewed plant performance.</p></header>
    <section className="grid gap-6 lg:grid-cols-3">{caseStudies.map((study) => <article id={study.slug} key={study.slug} className="flex flex-col overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><Image src={study.image} alt={`${study.industry} wastewater treatment case study`} width={720} height={430} loading="lazy" className="aspect-[16/10] w-full object-cover" /><div className="flex flex-1 flex-col p-5 sm:p-6"><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">{study.industry} · {study.capacity}</p><h2 className="mt-2 text-2xl font-black text-slate-950">{study.title}</h2><p className="mt-4 text-sm leading-6 text-slate-600"><strong className="text-slate-900">Challenge:</strong> {study.problem}</p><p className="mt-3 text-sm leading-6 text-slate-600"><strong className="text-slate-900">Nanozyme:</strong> {study.nanozyme}</p><div className="mt-5 grid grid-cols-2 gap-2">{study.metrics.slice(0, 4).map((metric) => <div key={metric.label} className="rounded-xl bg-slate-50 p-3"><span className="block text-xs font-bold text-slate-500">{metric.label}</span><span className="mt-1 block text-sm font-black text-emerald-700">{metric.after}</span><span className="text-[11px] text-slate-400">from {metric.before}</span></div>)}</div><details className="mt-4 rounded-xl border border-slate-200 p-3 text-sm"><summary className="cursor-pointer font-bold text-cyan-800">Implementation details</summary><p className="mt-3 leading-6 text-slate-600">{study.implementation}</p><blockquote className="mt-3 border-l-2 border-cyan-400 pl-3 italic text-slate-600">“{study.feedback}”</blockquote></details><div className="mt-auto flex flex-wrap gap-2 pt-5"><span className="inline-flex items-center gap-2 rounded-full border border-slate-300 px-3 py-2 text-xs font-bold text-slate-500"><Download className="h-4 w-4" />PDF Coming Soon</span><Link href="/#contact" className="inline-flex items-center gap-2 rounded-full bg-emerald-600 px-3 py-2 text-xs font-bold text-white"><PhoneCall className="h-4 w-4" />Consultation</Link></div></div></article>)}</section>
  </div></main>
}
