import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, CheckCircle2, FlaskConical, Gauge, Leaf, MessageCircle, ShieldCheck, Waves } from 'lucide-react'
import PageBreadcrumb from '@/components/ui/PageBreadcrumb'
import { createMetadata, siteConfig } from '@/lib/site'

export const metadata: Metadata = createMetadata({ title: 'Bioculture Manufacturer in India | Bionics Enviro Tech', description: 'Indian manufacturer of Nanozyme bioculture for ETP, STP, CETP and CSTP wastewater treatment. Compare performance and request a quote.', path: '/bioculture-manufacturer-in-india', keywords: ['Bioculture Manufacturer in India','Nanozyme Bioculture','Wastewater Bioculture Manufacturer','ETP Bioculture','STP Bioculture'] })

const specs=[['Available form','Organic semi-solid form'],['Bacterial strains','63 different bacterial strains'],['Stage of bacteria','Living bacteria'],['Bacterial colonies','63 × 10⁹ CFU/mL'],['Minimum shelf life','One year']]
const benefits=['Works across ETP, STP, CETP and CSTP applications','Accelerates biological BOD and COD breakdown','Can reduce sludge volume under suitable operating conditions','Organic, environment-conscious biological formulation','Helps reduce dependence on corrective chemical dosing','Supports recovery during high-load and shock conditions','Easy to apply within existing treatment processes']
const steps=[['Activates on contact','The living microbial consortium begins adapting after application under suitable plant conditions.'],['Breaks down organic load','Enzyme-producing microorganisms help convert biodegradable pollutants into simpler end products.'],['Maintains biomass stability','A diverse consortium supports recovery during changing organic or hydraulic loads.'],['Improves clarity and odour control','Better biological degradation supports clarity, lower TSS and odour control at source.']]
const comparison=[['Microbial strength','Basic aerobic or anaerobic strains','Selected multi-strain, enzyme-producing consortium'],['Action speed','Longer acclimatisation period','Plant response may begin within 24–72 hours'],['Shock-load handling','Limited tolerance in complex effluent','Supports biomass during toxicity and load variation'],['Operating range','Depends on narrow ideal conditions','Selected for broader conditions after assessment'],['Odour control','May treat odour after formation','Targets biological degradation of odour-forming compounds'],['Sludge generation','Incomplete digestion can increase sludge','Improved degradation may reduce sludge demand'],['Plant recovery','May be slower during restart','Suitable for recovery and biomass re-establishment'],['Form and storage','Commonly powder or liquid','Organic semi-solid with minimum one-year shelf life'],['Lifecycle cost','Lower initial price may require more time','Efficiency can support lower dosage and intervention'],['Best suited for','Simple domestic wastewater','Industrial and municipal ETP, STP, CETP and CSTP']]
const faqs=[['Is Nanozyme safe for the environment?','Nanozyme is an organic biological formulation. Follow supplied handling and dosing guidance.'],['Can it be used in low-pH or high-TDS conditions?','Selection depends on pH, TDS, toxicity and process configuration. Plant data should be reviewed first.'],['Is Nanozyme tested for wastewater treatment?','Formulations are supported by product specifications, laboratory knowledge and application experience.'],['How does it perform during the rainy season?','Performance depends on dilution, temperature, DO, retention time and hydraulic-load control.'],['Can it handle sudden hydraulic-load increases?','It supports biomass resilience, while equalisation and sound plant operation remain important.'],['Can it replace chemical dosing?','It can reduce dependence on some corrective chemicals but does not replace every treatment stage.'],['How quickly can BOD and COD change?','Initial response may appear within 24–72 hours; stable results depend on plant conditions.'],['What dosage is required?','Dosage depends on plant capacity, load, MLSS, DO, process design and treatment objective.'],['Is it suitable for sugar mills and distilleries?','Yes, with selection for the relevant aerobic or anaerobic treatment stage.'],['Can it be used in municipal CSTP and decentralised STP systems?','Yes, subject to plant assessment and appropriate formulation selection.'],['Is Nanozyme safe to handle?','Use the recommended PPE, storage instructions and applicable safety datasheet.'],['Can I request a consultation before ordering?','Yes. Share plant capacity, process flow and recent wastewater analysis for a recommendation.']]

export default function BiocultureManufacturerPage(){const whatsapp=siteConfig.phoneHref.replace(/\D/g,'');const schemas=[{'@context':'https://schema.org','@type':'Product',name:'Nanozyme Bioculture',brand:{'@type':'Brand',name:siteConfig.shortName},manufacturer:{'@type':'Organization',name:siteConfig.name},url:`${siteConfig.url}/bioculture-manufacturer-in-india`},{'@context':'https://schema.org','@type':'FAQPage',mainEntity:faqs.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))}];return <main className="bg-slate-50 pt-24 sm:pt-28">{schemas.map((schema,index)=><script key={index} type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>)}
<section className="mx-3 overflow-hidden rounded-[2rem] bg-gradient-to-br from-slate-950 via-[#092f3b] to-emerald-900 text-white sm:mx-5"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-10 sm:px-8 lg:grid-cols-[1.1fr_.9fr] lg:px-10 lg:py-16"><div><PageBreadcrumb dark items={[{label:'Bioculture Manufacturer in India'}]}/><p className="mt-8 text-xs font-bold uppercase tracking-[.2em] text-emerald-300">Scientific wastewater biotechnology</p><h1 className="mt-4 text-4xl font-black leading-tight sm:text-6xl">Bioculture Manufacturer in India</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-300">Bionics Enviro Tech manufactures Nanozyme Bioculture for industrial and municipal biological wastewater treatment.</p><Link href="/#contact" className="mt-7 inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-emerald-500 to-cyan-500 px-5 font-bold text-slate-950">Request Quote<ArrowRight className="h-5 w-5"/></Link></div><div className="rounded-3xl border border-white/15 bg-white/[.07] p-5 sm:p-7"><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-300">Nanozyme description</p><dl className="mt-4 divide-y divide-white/10">{specs.map(([term,value])=><div key={term} className="grid gap-1 py-3 sm:grid-cols-[.9fr_1.1fr]"><dt className="text-sm text-slate-300">{term}</dt><dd className="font-bold">{value}</dd></div>)}</dl></div></div></section>
<section className="mx-auto max-w-7xl px-5 py-12 sm:px-8 lg:px-10 lg:py-16"><div className="grid gap-6 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-700">About Bionics Enviro Tech</p><h2 className="mt-3 text-3xl font-black text-slate-950 sm:text-5xl">Scientific manufacturing built around practical plant performance</h2></div><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><p className="text-lg leading-8 text-slate-700">{siteConfig.name} develops and supplies research-based Nanozyme Bioculture for industrial and municipal wastewater treatment applications.</p><p className="mt-4 leading-7 text-slate-600">Our technical approach combines microbial formulation, wastewater assessment and application guidance for ETP, STP, CETP, CSTP, anaerobic digestion and organic-waste treatment.</p><div className="mt-6 grid gap-3 sm:grid-cols-3">{['Scientific manufacturing','Application-specific guidance','PAN India and export support'].map(item=><div key={item} className="flex gap-2 rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-900"><CheckCircle2 className="h-5 w-5 shrink-0 text-emerald-600"/>{item}</div>)}</div></div></div></section>
<section className="bg-white py-12 lg:py-16"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-700">Why Nanozyme</p><h2 className="mt-3 max-w-3xl text-3xl font-black text-slate-950 sm:text-5xl">A high-performance bioculture for demanding treatment plants</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{benefits.map(item=><article key={item} className="rounded-2xl border border-slate-200 p-5 shadow-sm"><CheckCircle2 className="h-6 w-6 text-emerald-600"/><h3 className="mt-4 font-bold leading-6">{item}</h3></article>)}</div></div></section>
<section className="py-12 lg:py-16"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-700">Biological mechanism</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">How Nanozyme works</h2><div className="mt-8 grid gap-4 lg:grid-cols-4">{steps.map(([title,text],index)=>{const icons=[FlaskConical,Waves,ShieldCheck,Gauge];const Icon=icons[index];return <article key={title} className="rounded-3xl border border-slate-200 bg-white p-6"><Icon className="h-7 w-7 text-emerald-600"/><h3 className="mt-5 text-xl font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p></article>})}</div></div></section>
<section className="mx-auto max-w-7xl px-5 pb-12 sm:px-8 lg:px-10"><div className="grid gap-6 rounded-3xl bg-emerald-950 p-6 text-white sm:p-8 lg:grid-cols-[.7fr_1.3fr]"><div><Leaf className="h-9 w-9 text-emerald-300"/><h2 className="mt-4 text-3xl font-black">Compliance made simpler</h2></div><div><p className="text-lg leading-8 text-slate-300">Nanozyme can support biological treatment aligned with plant discharge objectives and applicable pollution-control requirements.</p><p className="mt-3 text-sm text-slate-400">Compliance depends on the complete system and monitoring programme; product use alone does not guarantee compliance.</p></div></div></section>
<section className="bg-white py-12 lg:py-16"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-700">Technical comparison</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">Normal bioculture vs Nanozyme Bioculture</h2><div className="mt-8 overflow-x-auto rounded-3xl border border-slate-200"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-950 text-white"><tr><th className="p-4">Feature</th><th className="p-4">Normal bioculture</th><th className="p-4">Nanozyme Bioculture</th></tr></thead><tbody className="divide-y divide-slate-200">{comparison.map(row=><tr key={row[0]}><th className="p-4">{row[0]}</th><td className="p-4 text-slate-600">{row[1]}</td><td className="p-4 text-emerald-800">{row[2]}</td></tr>)}</tbody></table></div></div></section>
<section className="mx-auto max-w-5xl px-5 py-12 sm:px-8 lg:py-16"><p className="text-center text-xs font-bold uppercase tracking-[.2em] text-emerald-700">Frequently asked questions</p><h2 className="mt-3 text-center text-3xl font-black sm:text-5xl">Nanozyme application questions</h2><div className="mt-8 space-y-3">{faqs.map(([q,a])=><details key={q} className="rounded-2xl border border-slate-200 bg-white p-5"><summary className="cursor-pointer font-bold">{q}</summary><p className="mt-3 leading-7 text-slate-600">{a}</p></details>)}</div></section>
<section className="mx-3 mb-12 rounded-[2rem] bg-gradient-to-r from-emerald-600 to-cyan-600 px-5 py-10 text-center text-white sm:mx-5 lg:py-14"><h2 className="text-3xl font-black sm:text-5xl">Ready to discuss your treatment plant?</h2><p className="mx-auto mt-4 max-w-2xl text-white/85">Request a quotation and application recommendation for your wastewater conditions.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/#contact" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-white px-5 font-bold text-emerald-700">Request Quote<ArrowRight className="h-5 w-5"/></Link><a href={`https://wa.me/${whatsapp}`} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-white/30 px-5 font-bold"><MessageCircle className="h-5 w-5"/>WhatsApp</a></div></section>
</main>}
